output_dir: data/paraphrase_pass_at_n/baseline_qwen_2.5_7b/eval
paraphrases_path: data/paraphrase_pass_at_n/baseline_qwen_2.5_7b/paraphrases/paraphrases.json
prompt_keywords_path: hendrycks_math/prompts/direct_prompt_math.txt
model_type: base
model: Qwen/Qwen2.5-7B
temperature_even_index: 0.0
separator: "###"
solution_end: "\\boxed{"
max_steps: 1
max_tokens_per_step: 10000
engine: gllm
gllm_host: http://localhost:8181
gllm_load_model: true
evaluator: math
num_workers: 256
log_every: 20
